### ISSUE TITLE
I was glad to load your powerful, unique, cool, cool, nice, cool, inventive and genius mod for me, but suddenly there was unexpected twist and I am asking you for help.

### ISSUE THREAD

**Issue by marcelove30** [Pinary-Pi/Colored-Bricks-Minecraft-Mod#10]
I instaled forge 1.19 41.1.0 and put your mod in the mod folder then turned off and on again minecraft 1.19 and the mod loaded, it
showed me, but when I turned on world and on creative mode and there were on colored bricks. What happened again. Please help me.

**Comment by Pinary-Pi** [comment]
There were no colored bricks in the creative mode inventory or the bricks that you had previously placed when loading the world weren't there?
