### ISSUE TITLE
[1.18.2] Mod doesn't load correctly on dedicated server and causes crash.

### ISSUE THREAD

**Issue by StormDragon-64** [Pinary-Pi/Colored-Bricks-Minecraft-Mod#16]
This crash only occurs on dedicated servers. This is using the latest version of the Create+ modpack (which I am the creator of).
The server's crash report is available [here.](https://hastebin.com/share/ijegupimuh.perl)
I am using Minecraft 1.18.2 and Forge 40.2.0, with the 5.0 version of colored bricks. 
By the way, 4.3 doesn't have this issue.

**Comment by Charmanth** [comment]
Having the same issue on 1.19.2, it works fine in single player but as soon as I start a dedicated server on a host, crash!

Here is a [crash report](https://gist.github.com/Charmanth/a11be2b09fdd45048c04549771313a96) the server gives (Note I'm having same the same issue with CatJams, please don't look at it go "here's your problem!" problem is both mods are loading incorrectly in the server, but are loading correctly in singleplayer).

**Comment by Pinary-Pi** [comment]
Hi, this should no longer be an issue with 1.18 nor with other versions of Minecraft supported by Colored Bricks.
