### ISSUE TITLE
1.20.1 Mod isnt loading correctly on a dedicated server

### ISSUE THREAD

**Issue by Devilswarchild** [Pinary-Pi/Colored-Bricks-Minecraft-Mod#18]
mc version 1.20.1
mod version: coloredbricks-1.20-5.0.jar
forge version: 47.1.3

just tried to redo my test server to test a new update to my modpack and its crashing. crash report is labeling colored bricks as the culprit with the reason of its not loading correctly.

here is the crash report:

[crash-2023-08-22_18.55.36-fml.txt](https://github.com/Pinary-Pi/Colored-Bricks-Minecraft-Mod/files/12413808/crash-2023-08-22_18.55.36-fml.txt) (https://mclo.gs/TtziKWv for easier reading)

**Comment by albanecheri** [comment]
I have the same problem, did you find a solution ?

**Comment by Pinary-Pi** [comment]
This should no longer be a problem as long as with all version of Minecraft.
