### ISSUE TITLE
Just wanna say hi

### ISSUE THREAD

**Issue by wijiler** [Pinary-Pi/Colored-Bricks-Minecraft-Mod#5]

**Comment by wijiler** [comment]
yes i remember you i've been looking for a while

**Comment by wijiler** [comment]
my minecraft name for java is wijiler if you wanna play bw some time

**Comment by wijiler** [comment]
i code clients and this is some pretty poggers code

**Comment by Pinary-Pi** [comment]
I was wondering like wait theres another issue but its just you saying hi. lol @wijiler 
Btw my java is Pinary-Pi

**Comment by wijiler** [comment]
Ayyyyyy

**Comment by wijiler** [comment]
hypixel aight lets get on

**Comment by wijiler** [comment]
your name isnt registred on minecraft lmao
(i checked on name mc)

**Comment by Pinary-Pi** [comment]
> your name isnt registred on minecraft lmao
> (i checked on name mc)

Whoops I meant Pinary_Pi not Pinary-Pi

**Comment by Pinary-Pi** [comment]
> i code clients and this is some pretty poggers code

@wijiler My mod code is Poggers? Thanks it was pretty fun to code which makes me spend time on it which ig makes it poggers.

**Comment by wijiler** [comment]
lol im going to sleep soon cya soon <3

**Comment by wijiler** [comment]
(:

**Comment by Pinary-Pi** [comment]
How was your sleep? @wijiler

**Comment by wijiler** [comment]
good

**Comment by Pinary-Pi** [comment]
@wijiler I forgot to ask you if you have discord. It would be easier to communicate there.

**Comment by wijiler** [comment]
@Pinary-Pi  if you have reddit we could chat there (;

**Comment by Pinary-Pi** [comment]
> @Pinary-Pi if you have reddit we could chat there (;

I do have reddit! My user is [Pinary_Hello](https://www.reddit.com/user/Pinary_Hello).
