### ISSUE TITLE
Reply

### ISSUE THREAD

**Issue by marcelove30** [Pinary-Pi/Colored-Bricks-Minecraft-Mod#9]
Sorry to just write now, but I was away and couldn't write. I have read your message and reply. I have mods in minecraft 1.19. They
are burgermod 2.8.0-1.19, cfm-7.0.0-pre31-1.19, Clumps-forge-1.19-9.0.0+4, ironchest-1.19-14.0.2 and OptiFine_1.19_HD_U_H8.
I unpacked these mods and put your mod in and put your mod in and it didn't work either. And forge I have 1.19 
What is the problem. Please reply.

**Comment by Pinary-Pi** [comment]
Hello, I have recently done some testing myself and have found that if you are using an older version of forge, my mod will not work with it. Please make sure you have downloaded the most recent version of forge 1.19 which currently you can find here: https://files.minecraftforge.net/net/minecraftforge/forge/index_1.19.html
